version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_postgres_password_here
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-assistant-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - POSTGRES_URI=postgresql://postgres:5432/ai_assistant
      - JWT_SECRET=your_jwt_secret_here
      - GOOGLE_AI_API_KEY=your_google_ai_api_key_here
      - AI_INSTRUCTIONS=Your system instructions for the AI assistant
      - FAISS_INDEX_PATH=/path/to/faiss/index
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres-data:
